AWSTemplateFormatVersion: 2010-09-09
Description: ophan backfill step function
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: ophan
  App:
    Description: Application name
    Type: String
    Default: ophan-backfill
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: ophan-dist
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: params
          PolicyDocument:
            Statement:
              Effect: Allow
              Action: ssm:GetParameter
              Resource: [!Sub 'arn:aws:ssm:eu-west-1:021353022223:parameter/Ophan/backfill/${Stage}/google-creds.json']

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - lambda:InvokeFunction
                Resource: "*"

  InitJobLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-InitJob-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ophan/${Stage}/ophan-backfill/ophan-backfill.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: ophan backfill
      Handler: com.gu.ophan.backfill.InitBackfillStep::handleRequest
      MemorySize: 1024
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  QueryJobStateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-QueryJobState-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ophan/${Stage}/ophan-backfill/ophan-backfill.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: ophan backfill
      Handler: com.gu.ophan.backfill.AwaitQueryJobStep::handleRequest
      MemorySize: 1024
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  ExtractDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-ExtractData-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ophan/${Stage}/ophan-backfill/ophan-backfill.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: ophan backfill
      Handler: com.gu.ophan.backfill.ExtractDataStep::handleRequest
      MemorySize: 1024
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  AwaitExtractJobLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-AwaitExtractJobLambda-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ophan/${Stage}/ophan-backfill/ophan-backfill.jar
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: ophan backfill
      Handler: com.gu.ophan.backfill.AwaitExtractJobStep::handleRequest
      MemorySize: 1024
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 60

  OphanBackfillStepFunction:
    Type: "AWS::StepFunctions::StateMachine"
    DependsOn:
    - InitJobLambda
    - QueryJobStateLambda
    Properties:
      StateMachineName: Ophan-Backfill-Extractor
      DefinitionString:
        !Sub
          - |
           {
             "Comment": "Ophan backfill: data extractor (extracts data from the data lake)",
             "StartAt": "InitJob",
             "States": {
               "InitJob": {
                 "Type": "Task",
                 "Resource": "${InitJobArn}",
                 "Next": "PauseForQueryJobToRun"
                },
               "PauseForQueryJobToRun": {
                 "Type": "Wait",
                 "Seconds": 60,
                 "Next": "CheckQueryJobStatus"
               },
               "CheckQueryJobStatus": {
                 "Type": "Task",
                 "Resource": "${QueryJobStateArn}",
                 "Next": "IsQueryJobComplete"
               },
               "IsQueryJobComplete": {
                 "Type": "Choice",
                 "Choices": [
                   {
                     "Variable": "$.state",
                     "StringEquals": "RUNNING",
                     "Next": "PauseForQueryJobToRun"
                   },
                   {
                     "Variable": "$.state",
                     "StringEquals": "WAITING",
                     "Next": "ExtractDataStartJob"
                   },
                   {
                     "Variable": "$.state",
                     "StringEquals": "ERROR",
                     "Next": "ErrorInJob"
                   }
                 ],
                 "Default": "UnknownJobState"
               },
               "ExtractDataStartJob": {
                 "Type": "Task",
                 "Resource": "${ExtractDataArn}",
                 "Next": "PauseForExtractJobToRun"
               },
               "PauseForExtractJobToRun": {
                 "Type": "Wait",
                 "Seconds": 60,
                 "Next": "CheckExtractJobStatus"
               },
               "CheckExtractJobStatus": {
                 "Type": "Task",
                 "Resource": "${AwaitExtractJobArn}",
                 "Next": "IsExtractJobComplete"
               },
               "IsExtractJobComplete": {
                 "Type": "Choice",
                 "Choices": [
                   {
                     "Variable": "$.state",
                     "StringEquals": "RUNNING",
                     "Next": "PauseForExtractJobToRun"
                   },
                   {
                     "Variable": "$.state",
                     "StringEquals": "WAITING",
                     "Next": "JobComplete"
                   },
                   {
                     "Variable": "$.state",
                     "StringEquals": "ERROR",
                     "Next": "ErrorInJob"
                   }
                 ],
                 "Default": "UnknownJobState"
               },
               "UnknownJobState": {
                 "Type": "Fail",
                 "Cause": "Unrecognised job stats"
               },
               "ErrorInJob": {
                 "Type": "Fail",
                 "Cause": "$.error"
               },
               "JobComplete": {
                 "Type": "Succeed"
               }
             }
           }
          -
            InitJobArn: !GetAtt InitJobLambda.Arn
            QueryJobStateArn: !GetAtt QueryJobStateLambda.Arn
            ExtractDataArn: !GetAtt ExtractDataLambda.Arn
            AwaitExtractJobArn: !GetAtt AwaitExtractJobLambda.Arn
      RoleArn: !GetAtt StatesExecutionRole.Arn
